{% set name = "tomlplusplus" %}
{% set version = "3.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/marzer/tomlplusplus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fc1a5eb410f3c67e90e5ad1264a1386d020067cfb01b633cc8c0441789aa6cf2

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/toml++/toml.h  # [not win]
    - test -f ${PREFIX}/lib/cmake/tomlplusplus/tomlplusplusConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\toml++\toml.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\tomlplusplus\\tomlplusplusConfig.cmake exit 1  # [win]

about:
  home: https://github.com/marzer/tomlplusplus
  license: MIT
  license_file: LICENSE
  summary: Header-only TOML config file parser and serializer for C++17 (and later!).

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
